/*----------------------------------------------------------
   PMFORMAT.C -- Ein Formatierprogramm fÅr Disketten

   Help File Include

   Version 2.15 - 9.3.2000
   Version 2.16 - 4.5.2000
  ----------------------------------------------------------*/

#define PANEL_MAIN      1000        /* Hauptfenster */
#define PANEL_OPTIONS   1010        /* Optionen */
#define PANEL_WARNING   1020        /* Warnung */
#define PANEL_HFH       1030        /* Help for Help */
#define PANEL_DRIVE     1040        /* Hauptfenster: Disk */
#define PANEL_TYPE      1050        /* Hauptfenster: Typ  */
#define PANEL_FORMAT    1060        /* Hauptfenster: formatieren */
#define PANEL_LABEL     1070        /* Hauptfenster: Label */
#define PANEL_FMTTYPE   1080        /* Warnung: Formatierart */
#define PANEL_WARNOFF   1090        /* Warnung: Warnungen */
#define PANEL_BTNTYPE   1100        /* Optionen: Darstellung */
#define PANEL_CHECK     1110        /* Optionen: Format prÅfen */
#define PANEL_DSKDATA   1120        /* Diskettendaten */

